repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=100']
      - id: requirements-txt-fixer
      - id: no-commit-to-branch
        args: [--branch, staging, --branch, testing]

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        args:
          - --line-length=79
          - --target-version=py311
          - --skip-string-normalization
          - --diff
          - --color

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=79]

  - repo: local
    hooks:
      - id: gitleaks
        name: Detect hardcoded secrets
        description: Detect hardcoded secrets using Gitleaks
        entry: gitleaks detect
        language: system
        pass_filenames: false
