repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      #- id: fix-byte-order-marker
      #- id: check-executables-have-shebangs
      #- id: check-shebang-scripts-are-executable
      #- id: check-json
      #- id: pretty-format-json
      #- id: check-merge-conflict
      #- id: check-yaml
      #- id: check-symlinks
      #- id: end-of-file-fixer
      #- id: mixed-line-ending
      #- id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=100']
      #- id: detect-private-key
      #- id: detect-aws-credentials
      #- id: pretty-format-json
      - id: requirements-txt-fixer
      - id: no-commit-to-branch
        args: [--branch, staging,
               --branch, testing]

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black
        args: 
          - --line-length=79
          - --target-version=py311
          - --skip-string-normalization
          - --diff
          - --color

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
      args: [--max-line-length=79]
      # how to set in work on develop branch
      # exclude: '*/migrations/*'
