name: Generate Graphs and Update README

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate_graphs:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib requests

      # Run the script to generate graphs and README.md
      - name: Generate README.md
        run: create_graph_her_hour.py

      - name: Run graph generation script
        run: python create_github_pages.py

      # Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md graph/
          git commit -m "Update graphs and README.md"
          git push
          